name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build addon
        run: npm run build-addon

      - name: Build Electron app
        run: npm run build

      - name: Package Electron app
        run: npm run dist

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.{exe,dmg,AppImage}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
