name: Test GH_TOKEN Access

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-token:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check GH_TOKEN
        run: echo "GH_TOKEN is set"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Validate GH_TOKEN
        run: |
          if [ -z "$GH_TOKEN" ]; then
            echo "GH_TOKEN is not set";
            exit 1;
          else
            echo "GH_TOKEN is $GH_TOKEN";
          fi
