name: Test GH_TOKEN Access

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-token:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check GH_TOKEN
        run: echo "GH_TOKEN is set"
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Validate GH_TOKEN
        run: |
          if (-not $env:GH_TOKEN) {
            Write-Host "GH_TOKEN is not set"
            exit 1
          }
          else {
            Write-Host "GH_TOKEN is set"
          }
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
